### ISSUE TITLE
Thickness ISSUE

### ISSUE THREAD

**Issue by shalinsirwani** [mkazhdan/IsoSurfaceExtraction#3]
When I am comparing the result of the generated **.ply** file ( output of this tool ) . It seems to be much thick as compared to existing point cloud.

How to resolve this **thickness issue**

One more doubt :- I am providing  data in integer type between 0 to 255 ( XYZ values ).. Is it correct format??

**Comment by mkazhdan** [comment]
Can you share the point cloud?

**Comment by shalinsirwani** [comment]
Sorry that was some problem in that input data ,Its working fine :)
